# Generated by Django 2.1.4 on 2019-01-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('last_login', models.DateTimeField(blank=True, verbose_name='마지막 로그인')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'users',
            },
        ),
    ]
