# Generated by Django 2.1.4 on 2019-01-19 08:37

import apps.post.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=6, verbose_name='제목')),
                ('content', models.CharField(help_text='최대 30자 입력 가능', max_length=30, verbose_name='본문')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip', verbose_name='여행')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '포스트',
                'verbose_name_plural': '포스트들',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('image', models.ImageField(upload_to=apps.post.models.post_image_path, verbose_name='이미지')),
                ('order', models.SmallIntegerField(default=0, help_text='숫자가 작을수록 우선순위', verbose_name='순위')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post', verbose_name='포스트')),
            ],
            options={
                'verbose_name': '포스트 이미지',
                'verbose_name_plural': '포스트 이미지들',
                'db_table': 'post_images',
                'ordering': ['order'],
            },
        ),
    ]
